```javascript
// ... your Tailwind CSS configuration ...
module.exports = {
  // ... other configuration options ...
  purge: ['./src/**/*.html', './src/**/*.js'], // Or whatever your source files are
  // ... rest of the configuration ...
}
```